### ISSUE TITLE
DarkRP Shipments owned by player on spawn

### ISSUE THREAD

**Issue by bgpony** [roboderpy/dpp#11]
http://i.imgur.com/mCwcl06.png

**Comment by roboderpy** [comment]
Disable strict spawn checks

**Comment by bgpony** [comment]
21:29:42 - Server cvar 'dpp_strict_spawn_checks' changed to 0
Shipments still owned by players. Am I doing something wrong here?
http://i.imgur.com/XSttJtu.jpg
http://i.imgur.com/YhUl1bW.jpg
