### ISSUE TITLE
list of what each CAMI convar does?

### ISSUE THREAD

**Issue by Bryantdl7** [roboderpy/dpp#14]
Hello, I looked through bitbucket, github and steam workshop but could not find a list of convars and their specific uses. Is there something I am missing?

Thanks!

**Comment by PLPawkoW** [comment]
Well, if you check every option in DPP privileges the names of privileges in CAMI tell you what each privilege grants, so there's no need of a list in my opinion.

**Comment by roboderpy** [comment]
There are only CAMI privilege for every avaliable command, not for cvars. And every privilege is a privilege for console command except ```touchother``` privilege that is not a command.

**Comment by roboderpy** [comment]
As you can see there is a simple Lua list https://github.com/roboderpy/dpp/blob/master/lua/dpp/sh_access.lua#L101

**Comment by Bryantdl7** [comment]
Thanks for the list, and replying this quick.

First off, when I was hovering my mouse over each permission in the ulx permission manager it said something along the lines of 'enables or disables the selected feature' it didn't say what each permission does 

What I was looking for was a list that explains each permission like the little example I have below.

cleardecals - clears all client-side sprays, and paint 

I like to customize permissions available to each rank on my server and having a list explaining each commands use would prove helpful.

**Comment by roboderpy** [comment]
CAMI have no that sort of things like description. Second - https://github.com/TeamUlysses/ulx/issues/64 (Suggestion about current menu)
