### ISSUE TITLE
Restrictions seem to not be saving

### ISSUE THREAD

**Issue by Bryantdl7** [roboderpy/dpp#16]
Hello, as seen in my earlier message i imported from URS. anyways, after a server reboot all changes are lost, both restriction, and prop protection setting wise.

**Comment by roboderpy** [comment]
What the fuck

**Comment by roboderpy** [comment]
Are you using MySQL?

**Comment by Bryantdl7** [comment]
No I am not.

**Comment by roboderpy** [comment]
There seems to be a MySQL issue, but with SQL there is no problems (except that one table wasn't created)

**Comment by roboderpy** [comment]
Saves for me
