### ISSUE TITLE
Permissions not working correctly with ulib

### ISSUE THREAD

**Issue by bigdogmat** [roboderpy/dpp#17]
Ok, I was looking to restrict access to prop transfer functions (e.g. `transfertoplayer`), while doing so I removed access from all ranks except superadmin through ulx. Even though I removed access, all ranks were still able to use said functions.

I looked into the code to see who was at fault (dpp or ulx) and found it to be ulx, I would post this on their github, although I figured I'd let you considering this is directly related to your addon.

For an explanation of why this happens, and something you may want to pass on.

So the issue works like this. When a privilege is revoked from a player through ulx, it removes this privilege from the group table in `ULib.ucl.groups`. Because of that `ULib.ucl.query` returns nil, because it returns nil the `ULXCamiPlayerHasAccess` hook returns nothing which allows the default handler for CAMI to handle it. Considering MinAccess is defined as `user` it goes ahead and allows any player to use said function.

**Comment by roboderpy** [comment]
When CAMI admin mod Returning nil DPP thoughts that "admin mod got confused" and uses fallback - default access check.

**Comment by bigdogmat** [comment]
That's not the issue, ulib returns nil on the permission check, through this the default CAMI handler run which returns true and "Fallback."

**Comment by bigdogmat** [comment]
I'm only giving you this so you can pass it on to the ulib team

[This function](https://github.com/TeamUlysses/ulib/blob/master/lua/ulib/shared/cami_ulib.lua#L16-L24) doesn't return anything, because of that the [default CAMI handler](https://github.com/TeamUlysses/ulib/blob/master/lua/ulib/shared/cami_global.lua#L342-L362) runs

**Comment by roboderpy** [comment]
Oh. If it doesnt run callback, CAMI handles this.

**Comment by bigdogmat** [comment]
Indeed, and because of that ulx fails to handle the permissions. Again this isn't an issue on you side as far as I can tell

**Comment by bigdogmat** [comment]
If you'd like I could go ahead and report this as an issue on the ulib github, only noted you first because it's related to this

**Comment by roboderpy** [comment]
You know more infos about this + i am not at home right now

**Comment by bigdogmat** [comment]
Done https://github.com/TeamUlysses/ulib/issues/25

**Comment by roboderpy** [comment]
Fixed in ULib
