### ISSUE TITLE
[Bug/fix] Wire entities to not work when toolgun antispam is enabled

### ISSUE THREAD

**Issue by ickycoolboy** [roboderpy/dpp#18]
IF "enable toolgun antispam" in antispam options is enabled. Mostly all wire entities fail to work (This includes exploression2.

I did work up a very simple fix which involves editing the sh_hooks.lua file in lua/dpp.
On line 126 I changed debug.getlocal(i, 1) to debug.getlocal(1, i).
This fixes the issue.

My experience with glua is very minor. So please check this.

**Comment by roboderpy** [comment]
I added that because wire calls CanTool twice. It tries to detect whatever CanTool was actually called by a toolgun. Will look into that again

**Comment by roboderpy** [comment]
Will make chack whatever CanTool was called with WireLib.DummyTrace()

**Comment by roboderpy** [comment]
Also you changed debug.getlocal(i, 1) to debug.getlocal(1, i), in case of that, Should would never be true, because of that, no toolgun antispam at all
