### ISSUE TITLE
bad argument #3 to 'format' (no value)

### ISSUE THREAD

**Issue by Bryantdl7** [roboderpy/dpp#19]
Lua Error: [DPP - DBot Prop Protection] lua/dpp/sv_hooks.lua:46: bad argument #3 to 'format' (no value) 1. format - [C]:-1 2. LogSpawn - lua/dpp/sv_hooks.lua:46 3. PlayerSpawnedSENT - lua/dpp/sv_hooks.lua:432 4. CheckBefore - lua/dpp/sv_hooks.lua:235 5. PostEntityCreated - lua/dpp/sv_hooks.lua:851 6. unknown - lua/dpp/sv_hooks.lua:714

This might be related; it could also just be coincidence. I get this error and then my server freezes up, and then all clients get stuck at retrieving server info until reboot of server

**Comment by roboderpy** [comment]
It tells that model of entity is "no value". You have addon installed that adds broken spawnable entity. Anyway, will fix tomorrow (it is 22:15 for me)
