### ISSUE TITLE
[BUG] Owner HUD does not show up correctly 

### ISSUE THREAD

**Issue by ickycoolboy** [roboderpy/dpp#20]
(I tested this on a server with just ulib and ulx installed)

The owner HUD will randomly appear and disappear. It also seems to freeze until the prop is deleted.
This video demonstrates the problem easier.

http://puu.sh/tcTMx/24092ce129.mp4

**Comment by roboderpy** [comment]
Fucking gmod bugs. Will make workaround soon.

**Comment by roboderpy** [comment]
@ickycoolboy Also it is better to notify me about bugs in discord https://discord.gg/HG9eS79 (open bug on gitlab/github bug tracker and notify me in discord about bug)

**Comment by roboderpy** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2516

**Comment by roboderpy** [comment]
Fixed
