### ISSUE TITLE
MySQLoo silently fails to connect to database through localhost using UNIX socket on server start

### ISSUE THREAD

**Issue by bgpony** [roboderpy/dpp#6]
When we can get access to the virtual LUA loader it works, but otherwise, it isn't working and the server starts with DPP without configurations.

**Comment by roboderpy** [comment]
The problem is:
When server starts, if server is running on Linux and MySQL address is localhost, TMySQL4 tries to connect to MySQL server through socket. It fails. Then DMySQL3 tries to connect to localhost using MySQLoo, it fails silently (for some reason), and DMySQL3 falls back to SQLite
